from abc import ABC, abstractmethod
from typing import Dict, Any, Optional, Union
from modules.audio_guidance.models import AudioResult, AudioStatus


class AudioGuidanceInterface(ABC):
    """
    Abstract interface for Offline Audio Guidance in VisionGuide AI.
    Hardware-independent interface allowing pluggable TTS backends (pyttsx3/SAPI5, Android TTS, etc.)
    and audio output routing (Speakers, Bluetooth headsets).
    """

    @abstractmethod
    def initialize(self, config_dict: Optional[Dict[str, Any]] = None) -> bool:
        """
        Initialize TTS engine, background worker thread, audio queues, and hardware output.
        Returns True if successful, False otherwise.
        """
        pass

    @abstractmethod
    def speak_command(self, command: Union[str, Any], context: Optional[Dict[str, Any]] = None) -> AudioResult:
        """
        Convert structured navigation command (LEFT, RIGHT, FORWARD, STOP) or Module 09 DecisionResult
        to spoken text and schedule execution according to priority, repeat suppression, and safety overrides.
        """
        pass

    @abstractmethod
    def speak_message(self, message: str, priority: Union[str, int] = "NORMAL") -> AudioResult:
        """
        Queue or speak arbitrary text message with specified priority.
        """
        pass

    @abstractmethod
    def stop(self) -> None:
        """
        Immediately interrupt active speech playback and clear pending queues.
        """
        pass

    @abstractmethod
    def reset(self) -> None:
        """
        Reset queues, statistics, cooldown timers, and engine state.
        """
        pass

    @abstractmethod
    def get_statistics(self) -> Dict[str, Any]:
        """
        Return operational telemetry, counters, and metrics.
        """
        pass

    @abstractmethod
    def get_last_audio(self) -> Optional[AudioResult]:
        """
        Return the most recent AudioResult generated by the system.
        """
        pass

    @abstractmethod
    def is_available(self) -> bool:
        """
        Return whether audio guidance engine is ready and TTS/audio hardware is available.
        """
        pass

    # Optional helper methods for backward compatibility and control
    def pause(self) -> None:
        """Pause audio playback worker thread."""
        pass

    def resume(self) -> None:
        """Resume audio playback worker thread."""
        pass

    def set_volume(self, volume: float) -> bool:
        """Set speech volume (0.0 to 1.0)."""
        return True

    def set_rate(self, rate: int) -> bool:
        """Set speech rate (words per minute)."""
        return True

    def get_status(self) -> AudioStatus:
        """Return status snapshot."""
        return AudioStatus()
